name: beta

on:
  push:
    branches:
      - 'beta'
  workflow_dispatch: 

env:
  IMAGE: toddrob/searcharr
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: startsWith(github.ref, 'refs/heads/master')
        run: echo "TAG=latest" >> $GITHUB_ENV
      - if: startsWith(github.ref, 'refs/tags')
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      - name: upgrade apt packages..
        run: sudo apt-get update -y && sudo apt-get upgrade -y
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
          tags: toddrob/searcharr:latest
